#!/usr/bin/env python
# Script from here: https://dpaste.de/about/
 
import urllib
import urllib2
import sys
 
def paste_code():
  request = urllib2.Request(
    'https://dpaste.de/api/',
    urllib.urlencode([('content', sys.stdin.read())]),
  )
  response = urllib2.urlopen(request)
  # Strip surrounding quotes (NB: response has no trailing newline)
  print response.read()[1:-1]
 
if __name__ == '__main__':
  paste_code()
