#!/bin/sh

usage="
Convert nearly any multimedia file into the Opus format
Usage:
   opusconv -s speechaudio.wav
   opusconv -m music.mp3

Doesn't work with wildcards, to run over multiple files, use:
> for f in *.flac; do opusconv -m "$f"; done
Ensure that opus-tools and aviconv (ffmpeg) are installed.
Edit the --bitrate flag as needed 
"


while getopts 'm:s:' OPTION
do
  case $OPTION in
  m)
  	avconv -i "$OPTARG" -f wav - | opusenc --music --bitrate 94 - "$OPTARG.opus"
  	exit 2
		;;
  s)
		avconv -i "$OPTARG" -f wav - | opusenc --speech --bitrate 16 - "$OPTARG.opus"
		exit 2
		;;
  ?)	
    echo "$usage"
		exit 2
		;;
  esac
done





